### ISSUE TITLE
Unsupported JArray in querystring

### ISSUE THREAD

**Issue by hugosenari** [disruptek/sigv4#5]
When calling `getResources`  from atoz with `embed` should be an array but if we use array sigv4 complains about it

```
/home/hugosenari/.nimble/pkgs/sigv4-1.1.0/sigv4.nim(194) normalizeUrl
/home/hugosenari/.nimble/pkgs/sigv4-1.1.0/sigv4.nim(187) encodedQuery
/home/hugosenari/.nimble/pkgs/sigv4-1.1.0/sigv4.nim(178) toQueryValue
Error: unhandled exception: JArray unsupported [ValueError]
```

Sample code:
```nim
import asyncdispatch
import httpclient
import httpcore
import os
import json

import atoz/apigateway_20150709

when isMainModule:
  let
    apiResources = getResources.call(
      restapiId = paramStr(1),
      embed = %* ["methods"])
    response = waitfor apiResources.retry(tries=3)
    body = waitfor response.body
  if response.code.is2xx:
    echo response.code
    echo body
```

To be honest I'm not sure if it is a bug here and sigv4 should support array or at atoz that shouldn't expect an array from querystring.

edit: ~~query~~ querystring

**Comment by disruptek** [comment]
It looks like you're using this correctly; it's just a stupidly-designed AWS API.

The question is, how should we render a `JArray` when passed as a query string parameter?  We could join the values using `,` without breaking this particular use, but is that any more correct?

Any thoughts, @ThomasTJdev ?

_edit: for reference, the documentation for `GetResources` from API Gateway (2015)_
```nim
## parameters in `query` object:
##   embed: JArray
##        : A query parameter used to retrieve the specified resources embedded in the returned <a>Resources</a> resource in the response. This <code>embed</code> parameter value is a list of comma-separated strings. Currently, the request supports only retrieval of the embedded <a>Method</a> resources this way. The query parameter value must be a single-valued list and contain the <code>"methods"</code> string. For example, <code>GET /restapis/{restapi_id}/resources?embed=methods</code>.
##   position: JString
##           : The current pagination position in the paged result set.
##   limit: JInt
##        : The maximum number of returned results per page. The default value is 25 and the maximum value is 500.
```

**Comment by disruptek** [comment]
Another option would be to use the newer API Gateway, uh, API.  It doesn't suffer from this defect; it suffers from a _different_ use of a `JArray` during a `DELETE` call against tag keys... :grin:

**Comment by hugosenari** [comment]
I found some ways they describe array in querystring:

[.N of String](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_DescribeLoadBalancers.html#API_DescribeLoadBalancers_Examples)
> GET elasticloadbalancing.amazonaws.com/?Action=DescribeLoadBalancers
> &LoadBalancerArns.member.1=arn:aws:*:*:*:loadbalancer/app/lb1
> &LoadBalancerArns.member.2=arn:aws:*:*:*:loadbalancer/app/lb2
> &Version=2015-12-01
> &AUTHPARAMS

[.N of Key/Value](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeVpcPeeringConnections.html#API_DescribeVpcPeeringConnections_Example_2)
> GET ec2.amazonaws.com/?Action=DescribeVpcPeeringConnections
> &Filter.1.Name=tag:Name
> &Filter.1.Value.1=Finance
> &Filter.1.Value.2=Accounts
> &AUTHPARAMS

[Repeat](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_UntagResource.html#API_UntagResource_RequestSyntax)
>GET /v2/email/tags?ResourceArn=ResourceArn
> &TagKeys=Key1
> &TagKeys=Key2

[comma separated](https://docs.aws.amazon.com/apigateway/api-reference/link-relation/deployment-by-id/#template-variable)
> GET /restapis/{restapi_id}/deployments/{deployment_id}?embed=var1,var2

**Comment by disruptek** [comment]
That's super helpful, thanks.

In a sense, this is what my OpenAPI implementation is designed to help with.  The easiest solution might be to shim the validator like this:

```nim
# my nim may be rusty but this should give you the idea
import asyncdispatch
import httpclient
import httpcore
import os
import json

import atoz/apigateway_20150709

let validator = getResources.validator
getResources.validator = proc(path: JsonNode; query: JsonNode;
                                     header: JsonNode; formData: JsonNode;
                                     body: JsonNode; _: string = ""): JsonNode =
  # validate the input as usual to stuff it into a single node, etc.
  result = validator(path, query, header, formData, body, _)
  if "embed" in result["query"]:
    # recompose the JArray query field as a ,-separated JString
    result["query"]["embed"] = newJString:
      join(",", result["query"]["embed"].elems)

when isMainModule:
  let
    apiResources = getResources.call(
      restapiId = paramStr(1),
      embed = %* ["methods"])
    response = waitfor apiResources.retry(tries=3)
    body = waitfor response.body
  if response.code.is2xx:
    echo response.code
    echo body
```

Can you mess around with this a bit and see if it solves the problem for you?

**Comment by hugosenari** [comment]
Almost worked, except two things:
Your proposed join results in `"\"method\""`, changed with `result["query"]["embed"].to(seq[string]).join(",")` solved.

And it generates `https://apigateway.amazonaws.com/restapis/myApiId/resources?embed=methods&position&limit` those empty parameters cause: `Error: unhandled exception: 400 Bad Request`

Commenting it from call solves the problem:
```nim
proc call*(call_21627786: Call_GetResources_21627771; restapiId: string;
          embed: JsonNode = nil; position: string = ""; limit: int = 0): Recallable =
  var path_21627787 = newJObject()
  var query_21627788 = newJObject()
  if embed != nil:
    query_21627788.add "embed", embed
  # add(query_21627788, "position", newJString(position))
  # add(query_21627788, "limit", newJInt(limit))
  add(path_21627787, "restapi_id", newJString(restapiId))
  result = call_21627786.call(path_21627787, query_21627788, nil, nil, nil)
```

I'm not sure if atoz is fully generated (how you integrated sigv4?), and can't say it is a atoz bug or openapi bug.

Since I mixed all your projects in one bug, unrelated question, why rest isn't a nimble package?

Thank you, helped a lot.

**Comment by disruptek** [comment]
Well, you can pop out the empty parameters also to avoid having to edit the generated API by hand, but this isn't a bug -- it's a faithfully rendered OpenAPI definition that doesn't match the service's API.  Nothing we can do about it but add some logic to the API that we generate.

I believe `rest` isn't in the Nimble directory because there's already a package with that name, but `rest` is supposed to be replaced with the implementation of your choice -- it's just a temporary hack that grew to permanence as Nim never evolved the stdlib into something useful.

**Comment by disruptek** [comment]
I updated sigv4 to handle `JArray` by repeating the keys with new values; the code also includes values in the query string when supplied with `JInt` and such, as opposed to empty strings.

**Comment by disruptek** [comment]
Sorry, not sigv4.  This change is in openapi, so it applies to all API codegen.
